ssa_db_helper.c: Eliminate compilation errors
Warnings / errors of the following type are eliminated:

ssa_db_helper.c:849:10: error: ignoring return value of 'system',
declared with attribute warn_unused_result [-Werror=unused-result]
    system(buffer);

ssa_db_helper.c: In function 'ssa_db_rec_tbl_load_var_size':
ssa_db_helper.c:482:10: error: ignoring return value of 'fscanf',
declared with attribute warn_unused_result [-Werror=unused-result]
    fscanf(fd, "%c", &c);

Signed-off-by: Ilya Nelkenbaum <ilyan@mellanox.com>
Signed-off-by: Hal Rosenstock <hal@mellanox.com>